### PR TITLE
added Node-Butler to list

### PR DESCRIPTION
**Pull request by FidelVe**

### CODE REVIEW

**Comment by FidelVe** [comment]
@han-so1omon you recommended that I add a reviewer the next time I created a pull request but it seems that is not possible for me to do that because I dont have write access to the repo.

#8

**Comment by han-so1omon** [comment]
@FidelVe Interesting, I thought it would be possible. I have added myself as a reviewer. I will look into auto-assignment using [this configuration](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team)

**Comment by han-so1omon** [comment]
Great app btw!

**Comment by FidelVe** [comment]
> Great app btw!

thanks!

**Pull request merged**
